# Generated by Django 5.0.7 on 2024-08-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='contact',
        ),
    ]
